version: '3'

volumes:
  pg_data_production:
  static:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: gratefultolord/taski_backend
    env_file: .env
    volumes:
      - static:/backend_static
  frontend:
    image: gratefultolord/taski_frontend  # Качаем с Docker Hub
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  gateway:
    image: gratefultolord/taski_gateway  # Качаем с Docker Hub
    env_file: .env
    volumes:
      - static:/staticfiles/
    ports:
      - 8000:80